TARGET := iphone:clang:latest:7.0
INSTALL_TARGET_PROCESSES = 'Galaxy on Fire 2 HD'


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = FasterShips

FasterShips_FILES = Tweak.m
FasterShips_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
